### ISSUE TITLE
about COPYING file

### ISSUE THREAD

**Issue by hpfn** [jaraco/irc#106]
Hi,

irc in Debian is python-irc on 8.5.3+dfsg-2 version. I want
to update to the last version (14.2.2). But COPYING file
is missing.

The declared license is MIT. But the only reference to a
license it is a name in the setup.py file. That is not enough 
and I did a search and COPYING file in 12.1 declares 
LGPL license but setup.py file says MIT. It is confuse.
CHANGES.rst says MIT since 5.1.

In a next release, can you please, put a COPYING file
with the correct license ?

regards,
Herbert

**Comment by jaraco** [comment]
See #99. The project has been released anew under the MIT license since 5.1. The inclusion of the LGPL license was an unintended artifact (see c4fe0bdc3ffe). The declaration in the package metadata is clear and authoritative. Please rely on it.
