### ISSUE TITLE
IRCv3

### ISSUE THREAD

**Issue by lol768** [jaraco/irc#111]
Hey!

Is there any IRCv3 support at present with this library?

**Comment by jaraco** [comment]
Probably not. I'm not familiar with different IRC versions, but the core of this library goes back many years. If I had to guess, I'd expect IRCv3 to be largely backward compatible, so this library might still work with it, but perhaps not support all of the features. I encourage you to try it out, identify any shortcomings, and perhaps develop some improved support for it, if you're so inclined.

**Comment by real-or-random** [comment]
It supports CAP commands and message tags, see
https://github.com/jaraco/irc/blob/7c95b5e49ef19c3515a47d1a10b28790a58393a3/irc/client.py#L705
https://github.com/jaraco/irc/blob/41bb3e41953ef8a29278c7b50276438c297afd62/irc/message.py
