### ISSUE TITLE
regarding jaraco libraries

### ISSUE THREAD

**Issue by kutu** [jaraco/irc#122]
please add empty `__init__.py` file inside `jaraco` folder when installing via `pip install irc`
without that file `jaraco` package not being recognized as a python package, and for example `cx_Freeze` can't include it correctly when freezing application

**Comment by jaraco** [comment]
`jaraco` is a namespace package, and thus should not have the `__init__` (per PEP 420 and pip conventions). But if you look at the source, the file is there and it has a `declare_namespace` directive in it. It's pip that removes that file. You probably need to file a ticket with cx_Freeze to have it load the metadata for the installed packages to determine which packages are namespace packages.

**Comment by jaraco** [comment]
If you do find a jaraco.* package that doesn't have a `jaraco/__init__.py` in the source, that's a bug. But I don't think you'll find such a thing.
