### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by impredicative** [jaraco/irc#125]
https://pypi.python.org/pypi/irc/ does not make mention of Python 3.6 under the list Categories. Can it be added, assuming it is actually supported?

**Comment by jaraco** [comment]
Yeah, in my other projects, I just declare Python 3 support... and declare versions that are unsupported. This model of updating dozens of projects each time a Python version is released is absurd... so I'll just declare Python 3 support. The `python_requires` should defined the required Python versions.
