### ISSUE TITLE
AttributeError: 'module' object has no attribute 'client'

### ISSUE THREAD

**Issue by ghost** [jaraco/irc#126]
Trying to setup a simple client application by referring to the example apps but I'm getting the following error:

````
    reactor = irc.client.Reactor()
AttributeError: 'module' object has no attribute 'client'
````

Any idea what is going on? I'm using the python2 package, version 15.1.1 on archlinux.

**Comment by jaraco** [comment]
Did you `import irc.client`? That's what the example apps do.

**Comment by jaraco** [comment]
Also, see #124, which reported a similar error.

**Comment by ghost** [comment]
That worked, thanks.

**Comment by ResitK** [comment]
ModuleNotFoundError: No module named 'irc'
