### ISSUE TITLE
Broken IRC Specifications link

### ISSUE THREAD

**Issue by impredicative** [jaraco/irc#127]
The IRC Specifications link ( http://www.irchelp.org/irchelp/rfc/ ) at https://pypi.python.org/pypi/irc/ is broken. Anyway, is reading them really necessary? Users like abstraction :-)

**Comment by jaraco** [comment]
Someone else reported this in an e-mail. It's fixed in master.

**Comment by impredicative** [comment]
Looking forward to a new release on pypi whenever you think the time is right :)

**Comment by jaraco** [comment]
I just pushed a release. [16.0 is out now](https://pypi.org/project/irc/) with an updated link.
