### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by imaia** [jaraco/irc#130]
Take a look at these examples: https://github.com/kenkeiras/PyIC/blob/master/example.py They show how to complete a lot of common and quite useful tasks. It would be nice to have examples like those with this library.

**Comment by jaraco** [comment]
Sounds reasonable. Are you thinking they would go in the README? Can you draft the change in a PR?

**Comment by imaia** [comment]
I like very much how it was done within pyic, a single python file with the examples. README could just link to it, like: "For more usage examples, take a look at <link>". I'll make a simple PR with what I have in mind.

**Comment by jaraco** [comment]
Sounds good. I look forward to it.
