### ISSUE TITLE
Use better names than "c" and "e" for variables

### ISSUE THREAD

**Issue by farooqkz** [jaraco/irc#140]
the letters "c" and "e" doesn't tell the reader much about themselves and that what do they stand for.

**Comment by jaraco** [comment]
I agree. That convention was also used in pmxbot for some time.... and I never was sure if "c" was "client" or "connection". Can you send a pull request?

**Comment by farooqkz** [comment]
Not now. but I think "c" stands for connection.

**Comment by farooqkz** [comment]
@jaraco, Sorry for that.

**Comment by jaraco** [comment]
It's all good. You're right that this was the right thing to do.

**Comment by farooqkz** [comment]
I meant sorry for not sending a PR.
