### ISSUE TITLE
Functions Aren't Referenced?

### ISSUE THREAD

**Issue by PenguinzTech** [jaraco/irc#151]
Trying to figure out how to work with your library... currently writing a chat bot.
I see all of these "on_something" functions with no calls to them? How are they used?
Can I rename them to fit the rest of the program?

**Comment by jaraco** [comment]
on_* are called when the server transmits an event by that name. So when the server sends WELCOME, on_welcome is called

**Comment by jaraco** [comment]
So no, I don't think you can rename them.
