### ISSUE TITLE
I got error trying to run setup.py

### ISSUE THREAD

**Issue by jamieduk** [jaraco/irc#166]
root@jnet:/var/www/radio/irc-bot# python3 setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

shall I try  setup.py testbot after?
nope same error!

**Comment by researcx** [comment]
`pip install -e .` in the bot's folder worked for me

**Comment by baprx** [comment]
Hi, can you try that:

Requirements:
```
pip3 install wheel
pip3 install setuptools
```

Installation:
```
git clone https://github.com/jaraco/irc.git
cd irc
python3 setup.py sdist
./setup.py bdist_wheel
python3 setup.py build
sudo python3 setup.py install
```

**Comment by jaraco** [comment]
I would not ever recommend running `setup.py`. Always use `pip install` or `pip install -e`.
