### ISSUE TITLE
What's the unit of keepalive interval?

### ISSUE THREAD

**Issue by Urhengulas** [jaraco/irc#170]
I couldn't figure out what the unit of the `interval` in [`irc.client.set_keepalive(interval)`](https://python-irc.readthedocs.io/en/latest/irc.html#irc.client.ServerConnection.set_keepalive) is. I would assume seconds, but don't want to rely on a assumption.

I guess it is a good idea to add this information into the doc-string. _(Can take care of that of course)_

Thanks for the answer in advance :smiley:

**Comment by AiyionPrime** [comment]
Hey @Urhengulas, I just skimmed through the code:
set_keepalive() calls the reactors schedulers execute_every()s method,
which in turn calls (per the default-implementation) the method 'after' of PeriodicCommand imported with the [tempora](https://github.com/jaraco/tempora) package.
In it, PeriodicCommand inherits the said method from DelayedCommand.

['So as one can easily see' ](https://github.com/jaraco/tempora/blob/892e6314cc7e550ce8f95c51858cd1f22c531e05/tempora/schedule.py#L53) :D the parameter `delay` is expected to be either **seconds** as you suspected, but may even be a **datetime.timedelta** object if you feel like it.
This is true for all the earlier classes parameters that basically just hand the parameter through from `interval`.

Good luck with putting any of this in the docstring :)

**Comment by Urhengulas** [comment]
Thank you @AiyionPrime for your explanation. I just opened a small PR to add it to the docstring :smile:
