### ISSUE TITLE
How to get connection log?

### ISSUE THREAD

**Issue by Torxed** [jaraco/irc#181]
If for instance, when connecting to `irc.freenode.net` there's an issue during the connection phase that will go undetected. Subsequent [c.join()](https://github.com/jaraco/irc/blob/main/scripts/testbot.py#L42) in the testbot example will fail.

There's very little actual documentation on examples and such, just the doc strings and API source code as reference. But I can't seam to find a function/docstring mentioning the log or history.

Is it possible to debug why the join isn't working after the welcome message has arrived (which do arrive)?

**Comment by lord-carlos** [comment]
I am very novice when it comes to python. The following helped me a bit.
```python
import logging
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
```

But then I just see this:
```
DEBUG:irc.client:connect(server='chat.freenode.net', port=6697, nickname='wscrsfasd', ...)
DEBUG:irc.client:TO SERVER: NICK alskdfjadf
DEBUG:irc.client:TO SERVER: USER alskdfjadf 0 * :alskdfjadf
DEBUG:irc.client:process_forever(timeout=0.2)
DEBUG:irc.client:_dispatcher: disconnect
```

**Comment by Torxed** [comment]
> I am very novice when it comes to python. The following helped me a bit.
> 
> ```python
> import logging
> logging.basicConfig()
> logging.getLogger().setLevel(logging.DEBUG)
> ```
> 
> But then I just see this:
> 
> ```
> DEBUG:irc.client:connect(server='chat.freenode.net', port=6697, nickname='wscrsfasd', ...)
> DEBUG:irc.client:TO SERVER: NICK alskdfjadf
> DEBUG:irc.client:TO SERVER: USER alskdfjadf 0 * :alskdfjadf
> DEBUG:irc.client:process_forever(timeout=0.2)
> DEBUG:irc.client:_dispatcher: disconnect
> ```

That helps, I ended up triggering `on_endofmotd` as well as `on_welcome` hooks.
But I still don't get the connect log, but I simply just stopped caring and went on my way :)

**Comment by jaraco** [comment]
If there are events that are missing logging statements, I'd welcome improvements to that effect. As written, this issue is more of a question that's been answered. Thanks lord-carlos.
