### ISSUE TITLE
SASL example

### ISSUE THREAD

**Issue by rmblau** [jaraco/irc#230]
I am currently writing an irc client based on the SimpleIRCClient. How can I use the connect function's sasl_login parameter to successfully utilize SASL? I am trying to utilize it with libera.chat and I am struggling to figure out what string it needs to be set to  and if I need to do anything else to successfully login with SASL. I already have the password field set.

**Comment by jaraco** [comment]
I'm afraid I don't have an example. See https://github.com/jaraco/irc/issues/195 where support was added. Maybe that will give some hints about how to use it. If you figure it out, please consider sharing what you found (in this issue or in a docs PR) so others can benefit. Thanks!

**Comment by rmblau** [comment]
Yeah I'm struggling to figure out what it's expecting. Is it expecting a sasl_login=True? More work needs to be done on my end but I'll try and see if I can post an example once I get it working

**Comment by rmblau** [comment]
@jaraco okay so I've figured out sasl_login=True is good enough but I keep getting authentication failed for whatever reason. It's not super informative about what went wrong. No matter how I try to get it to work it never actually auths. Any ideas?

**Comment by jaraco** [comment]
Sounds like you figured it out, the 'sasl_login' needs to be the account name. I've updated the type hints to help signal that behavior as well.
