### ISSUE TITLE
Non-utf8 text causes crash

### ISSUE THREAD

**Issue by GIANTCRAB** [jaraco/irc#3]
`File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb7 in position 70: invalid start byte`

So apparently, the irc bot can be crashed when someone sends a non-utf8 to the IRC channel. The decoding should have some preventive checks or try catch exceptions or maybe use ISO instead. 

Please fix this issue. Thank you.

**Comment by jaraco** [comment]
Please see the "Decoding Input" section of the Readme. Also check the bug tracker on Bitbucket for others who have encountered this issue. Please comment on an issue there or raise a new one if you think the behavior should be different.
