### ISSUE TITLE
Update ref to README.rst in docs/index.rst

### ISSUE THREAD

**Issue by kunalg** [jaraco/irc#74]
Commit fbab7de6cdb011e876cb56ea7471005da3bf1a62 renamed the README.txt and CHANGES.txt files to .rst respectively.

The docs/history.rst has been updated with correct ref to CHANGES.rst.
However, docs/index.rst still points to '../README.txt'

No point sending a pull request for such a minor change.

**Comment by jaraco** [comment]
Got it, and done. Thanks.
