### ISSUE TITLE
Possible to use a password

### ISSUE THREAD

**Issue by pinghajen** [jaraco/irc#93]
Is it possible to use a password for `irc.bot.SingleServerIRCBot.__init__` Or how do I log in with a password?

**Comment by jaraco** [comment]
Sorry for the delay.

Yes, it's possible. Unfortunately, the docs aren't rendering the docstrings of the class, which indicate that the `server_list` parameter accepts tuples suitable for constructing `ServerSpec` objects, which take a host, port, and password. So pass something like `server_list = [('myserver', 6667, 'mysecret')]`.

Now that's if your server requires a password. If you need to send something like a Nickserv password, that's a different matter. For something like that, see what the [pmxbot project](https://github.com/yougov/pmxbot) does.
