### ISSUE TITLE
'module' object has no attribute 'buffer'

### ISSUE THREAD

**Issue by SteenSchutt** [jaraco/irc#97]
I moved my IRC bot (which is using this library) to another server, meaning a switch from Python 3.2 to 3.4. After installing irclib with pip, the buffer class seems to be missing. It's not in the dist-packages folder, while it is on my old server.
The error occurs when trying to use the LenientDecodingLineBuffer to parse UTF8 input.

```
irc.client.ServerConnection.buffer_class = irc.buffer.LenientDecodingLineBuffer
```

So yeah, basically the class doesn't exist anymore for some reason.

**Comment by jaraco** [comment]
In a late release of the irc lib, the buffer module was moved to jaraco.stream. It occurs to me that throb should maintain compatibility interfaces for this module. The quick fix is to downgrade irc lib (I'm unsure to which version specifically) or update your lib to use jaraco.stream.buffer.

Sorry for the inconvenience. I'll have a fix soon.

**Comment by SteenSchutt** [comment]
Ah, okay. Consider updating the readme so it reflects that. It was the reason I thought it was an error :)
