### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by aneeshusa** [jaraco/irc#99]
I couldn't find an indication of the license for this library. Could you please add a LICENSE file (and also mention it in the README and on the website)?

**Comment by jaraco** [comment]
License is OSI MIT as [indicated in the package metadata](/jaraco/irc/blob/master/setup.py#L60), mentioned in [the website](https://pypi.io/project/irc/). In this way, the license is listed in exactly one place and is machine consumable. I'd prefer not to add an additional file (and possible inconsistency). It doesn't seem unreasonable to indicate a reference to the license indicator in the readme, though I don't do that for most other projects.

**Comment by aneeshusa** [comment]
Thanks, I had been looking at the documentation website (https://pythonhosted.org/irc/) and didn't think to look at the setup.py file or PyPI.
